### ISSUE TITLE
Deadly Freeze of Death

### ISSUE THREAD

**Issue by QeDelphyn** [FinalForEach/Cosmic-Reach-Issue-Tracker#101]
Version: Any up to and including Pre-alpha 0.1.1
Specs: Ryzen 7 5700X, RX 6700XT, 32GB RAM, Win 10
Issue: Game freezes every time almost immediately after loading. The time can be prolonged (perhaps indefinitely) by pointing above the horizontal. During one or two among dozens of tries the game function (somewhat) normally for a minute or two before freezing.
There might be a slight correlation between chunk loading range and the immediacy of the freeze (the difference between <0.1 sec and 0.5 sec).
Logs: This bug produces no logs.
For more details see:
https://discord.com/channels/1198501071363002408/1215770408008286208

**Comment by 6rube** [comment]
Same Problem. Ryzen 7 3800X with a RX5700XT and 16GB RAM on Windows 10.

**Comment by justdogg** [comment]
Same here, Ryzen 5 3500X, RX 5700XT, 16GB RAM, Windows 10. AMD - related problem, i guess?..

**Comment by QeDelphyn** [comment]
As of 0.1.47 this issue seems to be resolved for me.

**Comment by FinalForEach** [comment]
@QeDelphyn I'm glad to hear it, I'm not sure what fixed it, since the game has undergone many overhauls since then, but it's good I can finally close this issue.
