### ISSUE TITLE
The last item on every page in the inventory is copied onto the next one

### ISSUE THREAD

**Issue by masik16u** [FinalForEach/Cosmic-Reach-Issue-Tracker#104]
https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/assets/79841266/726afce0-342f-450c-8b54-bde6c1dc9e62

**Comment by Fazin85** [comment]
that might not be a bug

**Comment by FinalForEach** [comment]
Fixed for 0.1.2
