### ISSUE TITLE
Black planes below ground

### ISSUE THREAD

**Issue by Lenni0451** [FinalForEach/Cosmic-Reach-Issue-Tracker#105]
In some Chunks black planes are rendered below the surface. Starting at the blocks and going down to the bottom of the world.
![grafik](https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/assets/20379977/120ce664-b89c-4786-a16c-f24e4f74bbe1)

Wireframe view of one chunk:
![grafik](https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/assets/20379977/71174d51-eb51-416d-8af5-97a21654a8be)

**Comment by FinalForEach** [comment]
Fixed during update 0.1.13
