### ISSUE TITLE
Water physics is tied to framerate

### ISSUE THREAD

**Issue by K3rhos** [FinalForEach/Cosmic-Reach-Issue-Tracker#106]
Everything in the title, water act differently depending on the framerate of the game.

This explain why some ppls get stuck in water blocks and some others on the contrary can launch themself into air.

https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/assets/30273537/acaa5e08-50b2-4a7b-855b-465029c6a667

**Comment by FinalForEach** [comment]
Fixed for 0.1.12
