### ISSUE TITLE
Inventory is shared and stays open in different worlds

### ISSUE THREAD

**Issue by masik16u** [FinalForEach/Cosmic-Reach-Issue-Tracker#108]
https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/assets/79841266/4767bba7-4f94-43e4-b761-477cbceefebf

Also, there is this strange-looking block, not sure if this is a bug

**Comment by gabecoatess** [comment]
That block is the debug block. It's used to prevent world corruption when mods are removed.
