### ISSUE TITLE
Falling at high speed causes the player to fall through blocks

### ISSUE THREAD

**Issue by masik16u** [FinalForEach/Cosmic-Reach-Issue-Tracker#112]
https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/assets/79841266/b63fbb25-7328-4e94-95c9-abe59bf58856

**Comment by ArnulfoRuiz** [comment]
It is repeated with the https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/issues/30

**Comment by masik16u** [comment]
Sorry, didn't see that one #30
