### ISSUE TITLE
Lights stack in intensity

### ISSUE THREAD

**Issue by IndySaigal** [FinalForEach/Cosmic-Reach-Issue-Tracker#126]
When I build straight up with light blocks, and the bottom most block is a different color than the rest, I notice that the intensity of the light increases beneath me. I'm not sure if this is intentional, but I thought I should let you know.
![e5abd8bb-3791-4022-816b-db65efa6ffb5](https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/assets/95194429/5037e26b-f30d-4926-a0ae-7311e10a6fb5)

**Comment by FinalForEach** [comment]
This is intentional due to the subtractive color system, but thank you for the report.
