### ISSUE TITLE
[macOS] [ARM] [JAR Version] World and items are completely invisible

### ISSUE THREAD

**Issue by roberttkahelin8** [FinalForEach/Cosmic-Reach-Issue-Tracker#128]
This is a cool game concept and amazing performance. However it seems the Mac really is incompatible with this game's renderer. UIs are functional and the world generates fine, but the renderer for items and levels doesn't seem to work at all. Physics are working, controls are working, and block breaking is working (can't tell if placement works because I can't see anything in the inventory to pick).
The outline also works, along with sound, saving/loading the world and saving/loading settings.

Notes:
I am using Java 17 to run the jar version of the game, as requested to do in the 'finale' video.
ARM Processor (contains the GPU as well, the specifics will be supplied if you need them).

And a screenshot of the window with a block outlined and the 'earth sky' and F3 menu.
<img width="512" alt="levelrendererbug" src="https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/assets/17255831/83d84480-47df-42a6-b96c-f4c4ca8bd7ce">

**Comment by SamuelDeboni** [comment]
I have the same issue, using arch-linux, CPU AMD Ryzen 7 2700X, GPU AMD ATI Radeon RX 580

Tried both Linux version and jar version with java 17

**Comment by FinalForEach** [comment]
> I have the same issue, using arch-linux, CPU AMD Ryzen 7 2700X, GPU AMD ATI Radeon RX 580
> 
> Tried both Linux version and jar version with java 17

Do you mind moving this to a separate issue? I believe the AMD linux is a regression, whereas the mac is always there.

**Comment by FinalForEach** [comment]
> I have the same issue, using arch-linux, CPU AMD Ryzen 7 2700X, GPU AMD ATI Radeon RX 580
> 
> Tried both Linux version and jar version with java 17

I'm getting reports that 0.1.14 fixed it for linux integrated, can you confirm on your part?

**Comment by SamuelDeboni** [comment]
> > I have the same issue, using arch-linux, CPU AMD Ryzen 7 2700X, GPU AMD ATI Radeon RX 580
> > Tried both Linux version and jar version with java 17
> 
> I'm getting reports that 0.1.14 fixed it for linux integrated, can you confirm on your part?

It fixes for me too, thanks!

**Comment by roberttkahelin8** [comment]
I thought I'd try a new version to see if anything improved for my end, but it didn't apparently. I've noticed there is an ARM-based set of libraries in the game files, however, perhaps there is something not right there?

**Comment by FinalForEach** [comment]
Should be fixed in the latest release, feel free to reopen if this is still an issue
