### ISSUE TITLE
Placing a vertical half slab can force the player down a block and clip into ground

### ISSUE THREAD

**Issue by carsongmiller** [FinalForEach/Cosmic-Reach-Issue-Tracker#129]
Haven't tested much, but here's a clip of it happening with vertical half slabs.

https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/assets/9277472/e08dadbb-cfcf-483a-ac72-df0a1705b0e7

**Comment by buezly** [comment]
https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/assets/166325474/e0c77c9c-3415-4616-82c1-93fb48aa2ec0

This was fixed with the latest changes to the movement.

**Comment by FinalForEach** [comment]
> 2024-04-25.13-33-45.mp4 
> This was fixed with the latest changes to the movement.

Great, closing the issue then!
