### ISSUE TITLE
Missing block (Possibly water?)

### ISSUE THREAD

**Issue by happyburger23** [FinalForEach/Cosmic-Reach-Issue-Tracker#132]
Summary: Empty space between Vertical Glass Slab and Grass Block

Game version:  Pre-alpha-0.1.20g
OS: Mac
Device Specs:  N/A
Game logs:  N/A
Potential workarounds: N/A

<img width="340" alt="Screenshot_2024-04-05_at_10 50 00_PM" src="https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/assets/93412223/407cc484-2f9f-4a5b-ab61-d4ec289fd3d9">

**Comment by FinalForEach** [comment]
Should be fixed with the latest release, feel free to re-open if this persists
