### ISSUE TITLE
"Open Save Directory" Causes

### ISSUE THREAD

**Issue by happyburger23** [FinalForEach/Cosmic-Reach-Issue-Tracker#133]
Summary: Pressing either "Open Save Directory" button (main menu, or pause menu) causes the game to stop responding. You cannot press any other button and it cannot be closed from the window. 

Game version: Pre-alpha-0.1.20g
OS: Mac
Device Specs: N/A
Game logs: N/A
Potential workarounds: N/A

**Comment by FinalForEach** [comment]
Closing this as I think it is fixed. Feel free to reopen if this issue persists.
