### ISSUE TITLE
Add fog as an option for zones

### ISSUE THREAD

**Issue by FinalForEach** [FinalForEach/Cosmic-Reach-Issue-Tracker#19]

**Comment by pietru2004** [comment]
fog should have gradient option along with noise 3d
gradient of some kind for defining what fog looks like above certain height, could be
underground dark_grayish -> surface almost no fog/fully transparent -> high in sky blueish

Noise 3D for getting concentration of fog in area, amount of fog you want in XYZ pos

Example from Godot Engine (OpenSource) https://docs.godotengine.org/en/stable/classes/class_fogvolume.html

**Comment by FinalForEach** [comment]
This is now directly tied to skies which are associated with zones, so this can be considered added now.
