### ISSUE TITLE
Repository is public

### ISSUE THREAD

**Issue by Lelebees** [FinalForEach/Cosmic-Reach-Issue-Tracker#26]
Maybe it is supposed to be, but i thought it might be nice to be warned if you didn't intend for this before the release of the "Remaking Minecraft" series finale, especially because of spoilers :)

I love the name! Cosmic Reach fits the theme of the game very well.

If you didn't intend for the name to be public yet, don't worry. Your secrets are safe with me :)

**Comment by FinalForEach** [comment]
It is, and thank you!
