### ISSUE TITLE
Support for non-QWERTY keyboards

### ISSUE THREAD

**Issue by FinalForEach** [FinalForEach/Cosmic-Reach-Issue-Tracker#36]
Names of keys in the keybinds menu are wrongly reported as what they would be in a QWERTY keyboard.

**Comment by TheOnlyJoeEnderman** [comment]
As a Colemak fan, thank you.

**Comment by TheOnlyJoeEnderman** [comment]
I'll give it a try in a couple hours.

**Comment by griddles** [comment]
With Workman layout, the movement keys are DASH, but are reported in the menu as WASD.

**Comment by TheOnlyJoeEnderman** [comment]
> With Workman layout, the movement keys are DASH, but are reported in the menu as WASD.
That's how it worked before for me on Colemak. The keys were WARS but the menu said WASD. Minecraft and Sea of Thieves do it the same way, so I am wondering if some games just know how to remap Colemak?

**Comment by Raechti** [comment]
The update didnt seem to fix it. I use a QWERTZ keyboard and the problem still remains exactly as described it in my bug report.

**Comment by Heehther** [comment]
The update fixed it! I use the Colemak layout.

**Comment by FinalForEach** [comment]
Does 0.1.6 fix it completely?
