### ISSUE TITLE
Starting a new keybind change doesn't stop an old one.

### ISSUE THREAD

**Issue by katarafett** [FinalForEach/Cosmic-Reach-Issue-Tracker#42]
If I left-click on Forward, then Backward, then Left, and then press 1, 2, and then 3, I get:

| Control  | Keybind|
|   ---    |   ---  |
| Forward  |    3   |
| Backward |    2   |
|   Left   |    1   |

![2024-03-08 20-40-49](https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/assets/88956326/82c26fce-3cc9-4478-8807-c8f80b3d1619)

---

Also, if I left-click on the same keybind at least 3 times without changing it, I can no longer interact with the hotbar except by using pick-block.

**Comment by FinalForEach** [comment]
Fixed for 0.1.4
