### ISSUE TITLE
Falling from a certain high makes you clip into the ground

### ISSUE THREAD

**Issue by miwafoxl** [FinalForEach/Cosmic-Reach-Issue-Tracker#49]
![Screenshot_4](https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/assets/44883301/1459f38c-e549-4e80-b806-c92dd00b9619)

**Version used:** Pre-Alpha 0.0.5 (windows-x64)

**Steps to reproduce:**
1. Fly to over 120 blocks+ from the base ground
2. Fall
3. Reaching the ground, the player will clip into the ground

It seems like this is tied to FPS. The lower your FPS, the higher the chances of clipping into the ground.

**Comment by ArnulfoRuiz** [comment]
Can you try with the version 0.0.6? And see if it keeps happening?

**Comment by miwafoxl** [comment]
> Can you try with the version 0.0.6? And see if it keeps happening?

Yep, still happens on 0.0.6.

**Comment by ArnulfoRuiz** [comment]
To replicate I had to raise Y 1k
![2024-03-08_21-23-15](https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/assets/79116477/13c47ecb-3ece-4d83-848e-915865bbc9e1)
![2024-03-08_21-23-34](https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/assets/79116477/734e6511-eb14-4270-9fd4-85045005c025)

**Comment by ArnulfoRuiz** [comment]
Reviewing the previous bugs, there is already one with this bug :c

https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/issues/30

**Comment by ArnulfoRuiz** [comment]
Reviewing the previous bugs, there is already one with this bug :c
https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/issues/30
If you can close the Issue

**Comment by miwafoxl** [comment]
> Reviewing the previous bugs, there is already one with this bug :c #30 If you can close the Issue

Oh, my bad! I'll close this one, thanks for pointing out!
