### ISSUE TITLE
Slabs force you to get stuck in the ceiling

### ISSUE THREAD

**Issue by katarafett** [FinalForEach/Cosmic-Reach-Issue-Tracker#50]
Walking up to a bottom slab when there is a block above you will push you into that block. Similarly, jumping under a top slab and placing a block beneath you will force you to get stuck in the top slab. Shifting to walk under a slab and then unshifting will also get you stuck in the block.

**Comment by ArnulfoRuiz** [comment]
True, it doesn't stay shifting when you're on a slab and you get stuck until you shift again.
V 0.0.6
![2024-03-08_21-01-58](https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/assets/79116477/517b4b6e-b2bb-43e1-aa03-b455fab8cf58)
![2024-03-08_21-02-08](https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/assets/79116477/1048f7d0-99de-4854-ba7b-cf250f0469b2)

**Comment by vrgtics** [comment]
i guess this game is from strongly for optimize the terrain afterall, and what matter is we need to first complete the rendering first, then we just start adjusing the player movement for later

**Comment by FinalForEach** [comment]
Should be fixed for 0.1.25
