### ISSUE TITLE
Breaking glass blocks and slabs turns them into ghosts V 0.0.6

### ISSUE THREAD

**Issue by ArnulfoRuiz** [FinalForEach/Cosmic-Reach-Issue-Tracker#52]
When a glass block or slab does not have any glass block around it and it breaks, it remains like a ghost. It is removed by adding another glass block nearby. With this you can also eliminate faces from the rendering and have glass panels :3

![2024-03-08_21-10-24](https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/assets/79116477/d752e106-ac6a-40ab-ac32-ad252ffe426b)
![2024-03-08_21-10-28](https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/assets/79116477/56618cdc-047e-4dd2-ad3d-542dcdb2cf0e)
![2024-03-08_21-10-37](https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/assets/79116477/8207816f-d2d8-4f21-8ea7-8194066387bb)

Only ghost block glass

![2024-03-08_21-12-57](https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/assets/79116477/ba2fc1d9-e5ea-4241-bfaa-c1ea27ca0d4e)

**Comment by katarafett** [comment]
The same thing happens with water.

**Comment by FinalForEach** [comment]
Fixed for 0.0.9!
