### ISSUE TITLE
Add the Far Lands

### ISSUE THREAD

**Issue by glowiak** [FinalForEach/Cosmic-Reach-Issue-Tracker#56]
It'd be nice to generate some sort of Far Lands in the distance. Right now the distance effects purely affect rendering, moving and all the rest except the world generation, that goes normally forever.

Also, thank you for switching away from GLSL 4. It really saves much patching.

**Comment by FinalForEach** [comment]
No problem on the GLSL 4 front. In regards to the far lands, I won't be adding terrain weirdness on purpose since the worldgen code is already a mess as it is, but thank you for the suggestion!
