### ISSUE TITLE
break blocks in inventory 

### ISSUE THREAD

**Issue by somethingcatchy2-school** [FinalForEach/Cosmic-Reach-Issue-Tracker#61]
When in the inventory you can still break and place block, even when clicking over the hot-bar.  
here is example: https://youtu.be/W56jpRfXE7I

**Comment by ArnulfoRuiz** [comment]
I think at the moment it's intentional.
If it is your same bug, don't forget to close this issue
https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/issues/28
