### ISSUE TITLE
Clicking a block in the inventory gives me both the block and a glowing slab

### ISSUE THREAD

**Issue by Braunii** [FinalForEach/Cosmic-Reach-Issue-Tracker#64]
![obraz_2024-03-09_154123345](https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/assets/110412027/7cd159e8-0be3-416a-8be2-af19f53982be)

**Comment by moon-phoenix42** [comment]
I also found this to be the case with the bottom grass slab giving you a side wooden slab.

**Comment by NickRas0ff** [comment]
For some blocks it seems to click in both inventory pages at once, giving both blocks to the player

**Comment by scoobydoofacethingdie** [comment]
that seems to have been fixed in pre-alpha-0.0.12
