### ISSUE TITLE
UI gets replaced with random block textures if water is the last item in the hotbar

### ISSUE THREAD

**Issue by NickRas0ff** [FinalForEach/Cosmic-Reach-Issue-Tracker#66]
![image](https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/assets/63860718/0c8ebbc8-0b71-482c-b9d7-72fe1955f00c)
![image](https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/assets/63860718/3818cec6-4beb-4fd4-8e4c-f476b40d6623)

**Comment by Samma2009** [comment]
i see i'm not the only one

**Comment by NickRas0ff** [comment]
Seems like water being in the hotbar causes it
