### ISSUE TITLE
You can uncrouch under a slab, causing you to get stuck

### ISSUE THREAD

**Issue by NickRas0ff** [FinalForEach/Cosmic-Reach-Issue-Tracker#72]
https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/assets/63860718/b0ad78e9-14cb-4271-94d5-79702154e9bf

Although you can easily get out by just crouching again, there still probably should be a check for that

**Comment by FinalForEach** [comment]
Should be fixed for 0.1.25
