### ISSUE TITLE
You can't click on the blocks in the last row of the inventory

### ISSUE THREAD

**Issue by NickRas0ff** [FinalForEach/Cosmic-Reach-Issue-Tracker#78]
![image](https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/assets/63860718/4ed8af12-8604-438d-8432-a694611153a7)

The blocks on the last row get highlighted when you hover over them, but can't be clicked

**Comment by FinalForEach** [comment]
Fixed for 0.1.1
