### ISSUE TITLE
Blocks shouldnt be brekable while in inventory

### ISSUE THREAD

**Issue by kristupas098** [FinalForEach/Cosmic-Reach-Issue-Tracker#79]

**Comment by Latioslvl47** [comment]
Agreed, especially because it lets you break and place blocks with the mouse cursor a bit further than you would otherwise be able to at certain angles.

**Comment by vrgtics** [comment]
#28 Clone: there are probably many people do not like this one as intended, while all the slab need to choose individually

**Comment by FinalForEach** [comment]
This is a intended feature.
