### ISSUE TITLE
Game cannot run faster than monitor

### ISSUE THREAD

**Issue by TheOnlyJoeEnderman** [FinalForEach/Cosmic-Reach-Issue-Tracker#89]
This may be an intentional feature, so you are free to close this issue. But the game cannot run a single FPS above my Monitor's refresh rate. well, occasionally it will say 86 when I unload stuff. but I think that is a visual bug and the game is trying to cap itself.

**Comment by andriemc** [comment]
Hey! This is not a bug, this is a feature, If you want the game's fps to go above your monitor's refresh rate, turn off `VSync` in the game's settings!

**Comment by Latioslvl47** [comment]
To be fair vsync isn't working right for me either, even with it off my game only runs and my monitor's refresh rate or lower

**Comment by andriemc** [comment]
> To be fair vsync isn't working right for me either, even with it off my game only runs and my monitor's refresh rate or lower

I guess that's the bug here...?

**Comment by vrgtics** [comment]
@andriemc it is seem to be the same when you turn `vsync` on/off, also the fps counter appear quite fast but i see the numbe stay about the same range

**Comment by andriemc** [comment]
> @andriemc it is seem to be the same when you turn `vsync` on/off, also the fps counter appear quite fast but i see the numbe stay about the same range

theres a possibility that the vsync option just doesnt do anything atm

**Comment by TheOnlyJoeEnderman** [comment]
I just realised I forgotnto mention that was with Vsync off. The game has no visible difference with Vsync on or off for me.

**Comment by andriemc** [comment]
> I just realised I forgotnto mention that was with Vsync off. The game has no visible difference with Vsync on or off for me.

hmm, There's two things that could be the issue: 1. It literally does nothing, 2. It only has effect when you restart.

Since some game engines require restarting the game to change the vsync option.

**Comment by FinalForEach** [comment]
Fixed as per 0.1.12
