### ISSUE TITLE
Blocks do not update when mined.

### ISSUE THREAD

**Issue by k754a** [FinalForEach/Cosmic-Reach-Issue-Tracker#92]
https://youtu.be/0O3s_zBe4WU
Sorry it doesn't let me send the video otherwise.

**Comment by ArnulfoRuiz** [comment]
What version are you dealing with?
And can you try to replicate it with version 0.1.0?

**Comment by k754a** [comment]
![image](https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/assets/114301997/1360b6cb-6546-4dee-8779-cf518ad58d25)

**Comment by ArnulfoRuiz** [comment]
Update your game and test if it is fixed, the current version is 0.1.2

**Comment by k754a** [comment]
Yea its seemed to fix it :) It kind of took a second to update, but that might be my gpu, Thank you :)

**Comment by ArnulfoRuiz** [comment]
Great, I would appreciate it if you would close the issue.

**Comment by k754a** [comment]
of course :)
