### ISSUE TITLE
Lighting artifacts on chunk boarders

### ISSUE THREAD

**Issue by kuandai** [FinalForEach/Cosmic-Reach-Issue-Tracker#97]
May be related to [this issue](https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/issues/25).

There are odd shadows on blocks on chunk borders, see attached image.
![Screenshot from 2024-03-09 15-29-20](https://github.com/FinalForEach/Cosmic-Reach-Issue-Tracker/assets/98203986/cfbdf9ec-5c07-4ab5-a9e0-523fce1dc44f)

**Comment by FinalForEach** [comment]
This issue has been fixed as per a recent update
